services:
  node-api:
    build: ./APIFestivo
    container_name: calendario-node
    ports:
      - "3030:3030"
    restart: always

  spring-api:
    build: ./festivos-api
    container_name: calendario-spring
    ports:
      - "8080:8080"
    restart: always
