spring.application.name=festivos-api
festivos.api.url=http://dockerapifestivos:3030/festivo/

spring.datasource.url=jdbc:postgresql://dockerdbcalendario:5432/festivo
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect